config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create], constraints: lambda { |req| req.format == :json }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :reservations, constraints: lambda { |req| req.format == :json }
  resources :tables, constraints: lambda { |req| req.format == :json }
  resources :restaurants, constraints: lambda { |req| req.format == :json }
  get '/check_availability' => 'reservations#check_availability', constraints: lambda { |req| req.format == :json }

  root 'restaurants#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :restaurant_id, :email, :password
  validates_uniqueness_of :email
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :user
	belongs_to :table
  accepts_nested_attributes_for :user
  validates_presence_of :table_id, :time, :group_size, :restaurant_id

  scope :today, -> { where("time >= ?", Time.zone.now.beginning_of_day) }
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :tables
	has_many :reservations
	belongs_to :user

	validates_uniqueness_of :name
end

app/models/table.rb
class Table < ActiveRecord::Base
	belongs_to :restaurant
	has_many :reservations

  validates_presence_of :restaurant_id, :persons

  def available?(req_time, persons)
    start = req_time - 60.minutes
    finish = req_time + 60.minutes
    min_people = persons.to_i - 1
    max_people = persons.to_i + 2
    !reservations.today.where(time: start..finish, group_size: min_people..max_people).present?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reservations

  validates_presence_of :name, :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  helper_method :available

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  def check_availability
    respond_to do |format|
      format.json { render json: { available: available.present? } }
    end
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    respond_to do |format|
      if available.present?
        user = User.find_by_email(params[:email])
        user = user.present? ? user : User.create(name: params[:name], email: params[:email])
        table = available.first
        r_params = { time: params[:time], group_size: params[:group_size], user_id: user.id, restaurant_id: table.restaurant_id, table_id: table.id }
        @reservation = Reservation.new(r_params)
        if @reservation.save
          format.json { render :show, status: :created, location: @reservation }
        else
          format.json { render json: @reservation.errors, status: :unprocessable_entity }
        end
      else
        format.json { render json: [] }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  def available
    available = Restaurant.find_by_id(params[:restaurant_id]).tables.reject do |o|
      o.available?(Time.parse(params[:time]), params[:group_size]) == false
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:table_id, :time, :group_size)
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :opening_hours)
    end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table, only: [:show, :edit, :update, :destroy]

  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
  end

  # GET /tables/new
  def new
    @table = Table.new
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(table_params)

    respond_to do |format|
      if @table.save
        format.json { render :show, status: :created, location: @table }
      else
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1
  # PATCH/PUT /tables/1.json
  def update
    respond_to do |format|
      if @table.update(table_params)
        format.json { render :show, status: :ok, location: @table }
      else
        format.html { render :edit }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def table_params
      params.require(:table).permit(:name, :min_occupants, :max_occupants, :restaurant_id)
    end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base

  private

    def user_params
      params.require(:user).permit(:name, :email, :phone, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reserve</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :table_id %><br>
    <%= f.text_field :table_id %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :group_size %><br>
    <%= f.text_field :group_size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Table</th>
      <th>Time</th>
      <th>Group size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.table_id %></td>
        <td><%= reservation.time %></td>
        <td><%= reservation.group_size %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Table:</strong>
  <%= @reservation.table_id %>
</p>

<p>
  <strong>Time:</strong>
  <%= @reservation.time %>
</p>

<p>
  <strong>Group size:</strong>
  <%= @reservation.group_size %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :opening %><br>
    <%= f.text_field :opening %>
  </div>
  <div class="field">
    <%= f.label :closing %><br>
    <%= f.text_field :closing %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Opening :</strong>
  <%= @restaurant.opening %>
</p>

<p>
  <strong>Closing:</strong>
  <%= @restaurant.closing %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

app/views/tables/_form.html.erb
<%= form_for(@table) do |f| %>
  <% if @table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
      <% @table.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :min_occupants %><br>
    <%= f.text_field :min_occupants %>
  </div>
  <div class="field">
    <%= f.label :max_occupants %><br>
    <%= f.text_field :max_occupants %>
  </div>
  <div class="field">
    <%= f.label :restaurant_id %><br>
    <%= f.text_field :restaurant_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tables/edit.html.erb
<h1>Editing Table</h1>

<%= render 'form' %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

app/views/tables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tables</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Min occupants</th>
      <th>Max occupants</th>
      <th>Restaurant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tables.each do |table| %>
      <tr>
        <td><%= table.name %></td>
        <td><%= table.min_occupants %></td>
        <td><%= table.max_occupants %></td>
        <td><%= table.restaurant_id %></td>
        <td><%= link_to 'Show', table %></td>
        <td><%= link_to 'Edit', edit_table_path(table) %></td>
        <td><%= link_to 'Destroy', table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Table', new_table_path %>

app/views/tables/new.html.erb
<h1>New Table</h1>

<%= render 'form' %>

<%= link_to 'Back', tables_path %>

app/views/tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @table.name %>
</p>

<p>
  <strong>Min occupants:</strong>
  <%= @table.min_occupants %>
</p>

<p>
  <strong>Max occupants:</strong>
  <%= @table.max_occupants %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @table.restaurant_id %>
</p>

<%= link_to 'Edit', edit_table_path(@table) %> |
<%= link_to 'Back', tables_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.notes %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @user.notes %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>